### ISSUE TITLE
CA not reporting percentages and stats to logs

### ISSUE THREAD

**Issue by RicHernandez2** [openplans/openblock#293]
Details:

CA in Bluemix cloud under light load is giving off many "Not available yet" messages.

Steps to repro:

```
Provision a set of blockchain servers with security enabled (CA, Va1, Va2) on Bluemix.com
Copy the name of that blockchain set to your manifest.yml file on the app.js home directory
Ensure the package.json contains a unique name for your app.js
Create a Node.js app
Bind the app to the blockchain set
cf push app.js
Select your blockchain set
Click launch
View logs
View CA logs Note the following:
```

2016-02-16T15:08:37.706862941Z % Total % Received % Xferd Average Speed Time Time Time Current

2016-02-16T15:08:37.706997172Z Dload Upload Total Spent Left Speed

Results:

% Stats are ostensibly written to logs with no values

Expected Results:

% Stats must have number values attached to them when written to log.

**Comment by katugtug** [comment]
This is the open block repo, not open block chain. Check the readme: https://github.com/openplans/openblock

**Comment by RicHernandez2** [comment]
Thanks
